apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-nginx
  minReplicas: 30
  maxReplicas: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
