apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-test
  template:
    metadata:
      labels:
        app: liveness-test
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 10; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
